### ISSUE TITLE
this.wechat4u.contacts.filter is not a function

### ISSUE THREAD

**Issue by einsqing** [wechaty/puppet-wechat4u#26]
`this.wechat4u.contacts.filter is not a function

2019-04-18 06:32:19:     at PuppetWechat4u.<anonymous> (/www/node_modules/wechaty-puppet-wechat4u/dist/src/puppet-wechat4u.js:641:18)

2019-04-18 06:32:19:     at Generator.next (<anonymous>)

2019-04-18 06:32:19:     at /www/node_modules/wechaty-puppet-wechat4u/dist/src/puppet-wechat4u.js:27:71

2019-04-18 06:32:19:     at new Promise (<anonymous>)

2019-04-18 06:32:19:     at __awaiter (/www/node_modules/wechaty-puppet-wechat4u/dist/src/puppet-wechat4u.js:23:12)

2019-04-18 06:32:19:     at PuppetWechat4u.roomList (/www/node_modules/wechaty-puppet-wechat4u/dist/src/puppet-wechat4u.js:638:16)

2019-04-18 06:32:19:     at PuppetWechat4u.<anonymous> (/www/node_modules/wechaty-puppet/dist/src/puppet.js:605:46)

2019-04-18 06:32:19:     at Generator.next (<anonymous>)

2019-04-18 06:32:19:     at /www/node_modules/wechaty-puppet/dist/src/puppet.js:25:71

2019-04-18 06:32:19:     at new Promise (<anonymous>)

2019-04-18 06:32:19:     at __awaiter (/www/node_modules/wechaty-puppet/dist/src/puppet.js:21:12)

2019-04-18 06:32:19:     at PuppetWechat4u.roomSearch (/www/node_modules/wechaty-puppet/dist/src/puppet.js:603:16)

2019-04-18 06:32:19:     at Function.<anonymous> (/www/node_modules/wechaty/dist/src/user/room.js:129:54)

2019-04-18 06:32:19:     at Generator.next (<anonymous>)

2019-04-18 06:32:19:     at /www/node_modules/wechaty/dist/src/user/room.js:7:71

2019-04-18 06:32:19:     at new Promise (<anonymous>)

2019-04-18 06:32:19:     at __awaiter (/www/node_modules/wechaty/dist/src/user/room.js:3:12)

2019-04-18 06:32:19:     at Function.findAll (/www/node_modules/wechaty/dist/src/user/room.js:122:16)

2019-04-18 06:32:19:     at Socket.<anonymous> (/www/app.js:120:39)

2019-04-18 06:32:19:     at process._tickCallback (internal/process/next_tick.js:`

**Comment by GotoLu** [comment]
请问this.wechat4u.contacts.filter is not a function这个问题解决了吗？

**Comment by sv-98-maxin** [comment]
> 请问this.wechat4u.contacts.filter is not a function这个问题解决了吗？
应该是不解决了吧

**Comment by leochen-g** [comment]
> 请问this.wechat4u.contacts.filter is not a function这个问题解决了吗？

最新版已经解决
