### ISSUE TITLE
forward picrure always fail.

### ISSUE THREAD

**Issue by JuoJuo** [wechaty/puppet-wechat4u#43]
### forward picrure always fail.

```js
15:56:01 ERR Message forward(Room<测试2>) exception: AssertionError [ERR_ASSERTION]: -1 == 0
15:56:01 ERR Message forward(Room<测试2>) exception: AssertionError [ERR_ASSERTION]: -1 == 0
uncaughtException AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (C:\Users\HASEE\Desktop\robot-wx\node_modules\.pnpm\wechat4u@0.7.8\node_modules\wechat4u\lib\util\global.js:69:24)
    at C:\Users\HASEE\Desktop\robot-wx\node_modules\.pnpm\wechat4u@0.7.8\node_modules\wechat4u\lib\core.js:931:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageForward (C:\Users\HASEE\Desktop\robot-wx\node_modules\.pnpm\wechaty-puppet-wechat4u@1.13.11_wechaty-puppet@1.20.2\node_modules\wechaty-puppet-wechat4u\dist\cjs\src\puppet-wechat4u.js:669:9)
    at async WechatifiedUserClass.forward (C:\Users\HASEE\Desktop\robot-wx\node_modules\.pnpm\wechaty@1.20.2\node_modules\wechaty\dist\cjs\src\user-modules\message.js:780:27)
    at async C:\Users\HASEE\Desktop\robot-wx\src\onLogin.js:76:17
    at async iterateToRooms (C:\Users\HASEE\Desktop\robot-wx\src\onLogin.js:38:7)
    at async C:\Users\HASEE\Desktop\robot-wx\src\onLogin.js:75:15 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: -1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '转发消息失败'
}
```

**Comment by leochen-g** [comment]
ok, I will check it

**Comment by JuoJuo** [comment]
thanks

**Comment by JuoJuo** [comment]
@leochen-g 
have you found out why?

**Comment by leochen-g** [comment]
> @leochen-g have you found out why?

I've tested it and found no problems. Perhaps you need to give a mini case.

**Comment by JuoJuo** [comment]
"wechaty": "^1.0.0",
    "wechaty-puppet-wechat4u": "^1.13.11"

```js
const { WechatyBuilder } = require('wechaty');
const { PuppetWechat4u } = require('wechaty-puppet-wechat4u');

const wechaty = WechatyBuilder.build({
  puppet: new PuppetWechat4u(),
  name: 'www',
});
wechaty
  .on('scan', (qrcode, status) =>
    console.log(
      `Scan QR Code to login: ${status}\nhttps://wechaty.js.org/qrcode/${encodeURIComponent(
        qrcode
      )}`
    )
  )
  .on('login', user => console.log(`User ${user} logged in`))
  .on('message', async msg => {
    const room = msg.room();
    if (msg.type() === wechaty.Message.Type.Image) {
      await msg.forward(room);
    }
  });
wechaty.start();

```


@leochen-g 
by the  way can you give me a starter code for forward img?

**Comment by leochen-g** [comment]
#https://github.com/nodeWechat/wechat4u/pull/309

I have submitted PR to wechat4u, please keep following.

**Comment by leochen-g** [comment]
It is normal for you to forward messages from contacts

**Comment by JuoJuo** [comment]
@leochen-g 
thanks！
It works fine. 👍
