### ISSUE TITLE
启动登录之后一段时间就会报uncaughtException GError这个错误

### ISSUE THREAD

**Issue by AKG-0501** [wechaty/puppet-wechat4u#59]
uncaughtException GError: 状态同步超过300s未响应，5s后尝试重启
    at Wechat.checkPolling (/opt/getting-started-main/node_modules/wechat4u/lib/wechat.js:298:19)
    at Timeout._onTimeout (/opt/getting-started-main/node_modules/wechat4u/lib/wechat.js:319:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: 状态同步超过300s未响应，5s后尝试重启\n' +
    '    at Wechat.checkPolling (/opt/getting-started-main/node_modules/wechat4u/lib/wechat.js:298:19)\n' +
    '    at Timeout._onTimeout (/opt/getting-started-main/node_modules/wechat4u/lib/wechat.js:319:25)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}
这是因为网络问题吗？

**Comment by c517718004** [comment]
uncaughtException GError: 状态同步超过219.301s未响应，5s后尝试重启
    at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19)
    at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: 状态同步超过219.301s未响应，5s后尝试重启\n' +
    '    at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19)\n' +
    '    at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by AKG-0501** [comment]
> uncaughtException GError: 状态同步超过219.301s未响应，5s后尝试重启 at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19) at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) { code: 2, details: 'Error: 状态同步超过219.301s未响应，5s后尝试重启\n' + ' at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19)\n' + ' at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25)\n' + ' at listOnTimeout (node:internal/timers:559:17)\n' + ' at processTimers (node:internal/timers:502:7)' }
有解决办法吗

**Comment by c517718004** [comment]
> > uncaughtException GError: 状态同步超过219.301s未响应，5s后尝试重启 at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19) at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25) at listOnTimeout (node:internal/timers:559:17) at processTimers (node:internal/timers:502:7) { code: 2, details: 'Error: 状态同步超过219.301s未响应，5s后尝试重启\n' + ' at Wechat.checkPolling (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:298:19)\n' + ' at Timeout._onTimeout (/data/wwwroot/btzz.bentuyilian.com/wechatbot/node_modules/wechat4u/lib/wechat.js:319:25)\n' + ' at listOnTimeout (node:internal/timers:559:17)\n' + ' at processTimers (node:internal/timers:502:7)' }
> > 有解决办法吗

还没有

**Comment by zhengxs2018** [comment]
我挂服务器，用 node 20 经常这样，但我改用 node 18 已经稳定2周了。

**Comment by why-qw1ko** [comment]
> 我挂服务器，用 node 20 经常这样，但我改用 node 18 已经稳定2周了。

改用18以后最长稳定了多久啊？
