### ISSUE TITLE
新注册的微信号无法登陆

### ISSUE THREAD

**Issue by shavingha** [wechaty/puppet-wechat4u#69]
新申请的账号扫码的时候报错。
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/workspace/getting-started/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /workspace/getting-started/node_modules/wechat4u/src/core.js:194:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

**Comment by zhengxs2018** [comment]
新注册的，需要实名认证，不然无法登录的。

你的是这个问题么？
